
package SonyClient.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SonyServiceService", targetNamespace = "http://SonyService/", wsdlLocation = "http://localhost:9000/SonyService?wsdl")
public class SonyServiceService
    extends Service
{

    private final static URL SONYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SONYSERVICESERVICE_EXCEPTION;
    private final static QName SONYSERVICESERVICE_QNAME = new QName("http://SonyService/", "SonyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/SonyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SONYSERVICESERVICE_WSDL_LOCATION = url;
        SONYSERVICESERVICE_EXCEPTION = e;
    }

    public SonyServiceService() {
        super(__getWsdlLocation(), SONYSERVICESERVICE_QNAME);
    }

    public SonyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SONYSERVICESERVICE_QNAME, features);
    }

    public SonyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SONYSERVICESERVICE_QNAME);
    }

    public SonyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SONYSERVICESERVICE_QNAME, features);
    }

    public SonyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SonyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SonyService
     */
    @WebEndpoint(name = "SonyServicePort")
    public SonyService getSonyServicePort() {
        return super.getPort(new QName("http://SonyService/", "SonyServicePort"), SonyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SonyService
     */
    @WebEndpoint(name = "SonyServicePort")
    public SonyService getSonyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SonyService/", "SonyServicePort"), SonyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SONYSERVICESERVICE_EXCEPTION!= null) {
            throw SONYSERVICESERVICE_EXCEPTION;
        }
        return SONYSERVICESERVICE_WSDL_LOCATION;
    }

}
