
package SonyClient.proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SonyService", targetNamespace = "http://SonyService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SonyService {


    /**
     * 
     * @param id
     * @return
     *     returns SonyClient.proxy.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovie", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.GetMovie")
    @ResponseWrapper(localName = "getMovieResponse", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.GetMovieResponse")
    @Action(input = "http://SonyService/SonyService/getMovieRequest", output = "http://SonyService/SonyService/getMovieResponse")
    public Movie getMovie(
        @WebParam(name = "Id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns SonyClient.proxy.Song
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSong", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.GetSong")
    @ResponseWrapper(localName = "getSongResponse", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.GetSongResponse")
    @Action(input = "http://SonyService/SonyService/getSongRequest", output = "http://SonyService/SonyService/getSongResponse")
    public Song getSong(
        @WebParam(name = "Id", targetNamespace = "")
        int id);

    /**
     * 
     * @param movie_0020List
     */
    @WebMethod
    @RequestWrapper(localName = "sendMovies", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendMovies")
    @ResponseWrapper(localName = "sendMoviesResponse", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendMoviesResponse")
    @Action(input = "http://SonyService/SonyService/sendMoviesRequest", output = "http://SonyService/SonyService/sendMoviesResponse")
    public void sendMovies(
        @WebParam(name = "Movie List", targetNamespace = "")
        List<Movie> movie_0020List);

    /**
     * 
     * @param songJava_0020List
     */
    @WebMethod
    @RequestWrapper(localName = "sendSongs", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendSongs")
    @ResponseWrapper(localName = "sendSongsResponse", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendSongsResponse")
    @Action(input = "http://SonyService/SonyService/sendSongsRequest", output = "http://SonyService/SonyService/sendSongsResponse")
    public void sendSongs(
        @WebParam(name = "Song.java List", targetNamespace = "")
        List<Song> songJava_0020List);

    /**
     * 
     * @param user_0020Activity_0020List
     */
    @WebMethod
    @RequestWrapper(localName = "sendUserActivity", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendUserActivity")
    @ResponseWrapper(localName = "sendUserActivityResponse", targetNamespace = "http://SonyService/", className = "SonyClient.proxy.SendUserActivityResponse")
    @Action(input = "http://SonyService/SonyService/sendUserActivityRequest", output = "http://SonyService/SonyService/sendUserActivityResponse")
    public void sendUserActivity(
        @WebParam(name = "User Activity List", targetNamespace = "")
        List<UserActivity> user_0020Activity_0020List);

}
